// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6hS6iQOJeIsklYMJ6oXR6f2OFJ7bNNV8',
    appId: '1:99232858415:web:102c9a3ccf2a55fa82e1da',
    messagingSenderId: '99232858415',
    projectId: 'kitchenmanagment-f969c',
    authDomain: 'kitchenmanagment-f969c.firebaseapp.com',
    storageBucket: 'kitchenmanagment-f969c.firebasestorage.app',
    measurementId: 'G-WLML16FZTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANN8kH5ZBLbJ5X0vW8VslJW9l09NuUGyY',
    appId: '1:99232858415:android:18af85c696a8d2b782e1da',
    messagingSenderId: '99232858415',
    projectId: 'kitchenmanagment-f969c',
    storageBucket: 'kitchenmanagment-f969c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQ-scEGhscyDSXCYZ7NjeG-FG6sW2I-U',
    appId: '1:99232858415:ios:ddebb926e10c458482e1da',
    messagingSenderId: '99232858415',
    projectId: 'kitchenmanagment-f969c',
    storageBucket: 'kitchenmanagment-f969c.firebasestorage.app',
    iosBundleId: 'com.ramadan.kitchen.app.ramadanKitchenManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhQ-scEGhscyDSXCYZ7NjeG-FG6sW2I-U',
    appId: '1:99232858415:ios:ddebb926e10c458482e1da',
    messagingSenderId: '99232858415',
    projectId: 'kitchenmanagment-f969c',
    storageBucket: 'kitchenmanagment-f969c.firebasestorage.app',
    iosBundleId: 'com.ramadan.kitchen.app.ramadanKitchenManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6hS6iQOJeIsklYMJ6oXR6f2OFJ7bNNV8',
    appId: '1:99232858415:web:d23ad89bfd0cfff782e1da',
    messagingSenderId: '99232858415',
    projectId: 'kitchenmanagment-f969c',
    authDomain: 'kitchenmanagment-f969c.firebaseapp.com',
    storageBucket: 'kitchenmanagment-f969c.firebasestorage.app',
    measurementId: 'G-2TLX2KZE6C',
  );
}
